[project]
name = "urssi-notes"
version = "0.1.0"
description = "Add a short description here"
authors = ["Andreas Copan <avcopan@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
pip = ">=24.0,<25"
python = ">=3.12.4,<3.13"
